google/slo-generator

- .github/workflows/release-please.yml
Reverts google/slo-generator#18
> Revert "build: Add correct author to release-please"

- slo_generator/backends/elasticsearch.py
- slo_generator/backends/prometheus.py
- slo_generator/backends/stackdriver.py
- slo_generator/utils.py
Move of PR: https://github.com/GoogleCloudPlatform/professional-services/pull/489
> Add exc_info to logging.

- .github/workflows/release.yml
Workflow named 'release' clashes with release-please.
> fix: change release workflow name

- setup.py
- slo_generator/utils.py
> fix: correct get_human_timestamp

- docs/prometheus.md
- samples/prometheus/slo_prom_metrics_availability_query_sli.yaml
- samples/prometheus/slo_prom_metrics_availability_ratio.yaml
- samples/prometheus/slo_prom_metrics_latency_distribution_cut.yaml
- samples/prometheus/slo_prom_metrics_latency_query_sli.yaml
- slo_generator/backends/prometheus.py
This PR:
- Fixes the `good_bad_ratio` method giving inaccurate results
- Improve documentation for `good_bad_ratio`
- Add ability to specify which PromQL functions will be applied for `good_bad_ratio`
- Add `distribution_cut` method to compute SLOs based on histograms
- Add documentation for `distribution_cut`
> feat: Prometheus backend improvements

- slo_generator/backends/elasticsearch.py
- slo_generator/backends/prometheus.py
- slo_generator/backends/stackdriver.py
- slo_generator/backends/stackdriver_service_monitoring.py
- slo_generator/compute.py
- slo_generator/constants.py
- slo_generator/exporters/bigquery.py
- slo_generator/report.py
- tests/unit/test_report.py
- tests/unit/test_stubs.py
Fixes #42 
Adds additional validation mechanisms to return a good error message when the backend results are invalid.
> fix: SLO Report validation

- samples/README.md
- samples/custom/custom_stackdriver.py
- samples/custom/slo_gae_app_latency.yaml
- slo_generator/cli.py
- slo_generator/utils.py
- tests/unit/test_utils.py
Move from: https://github.com/GoogleCloudPlatform/professional-services/pull/517
> Allow user to define his own backend.

- .github/workflows/build.yml
- slo_generator/constants.py
- slo_generator/report.py
- tests/unit/test_report.py
- tests/unit/test_stubs.py
avoid breaking existing setups that have low number of events
> fix: Set min_valid_events to 1

- setup.py
- slo_generator/backends/dynatrace.py
- slo_generator/exporters/dynatrace.py
- tests/unit/fixtures/dt_error_rate.json
- tests/unit/test_compute.py
- tests/unit/test_stubs.py
> fix: Dynatrace fixes

- slo_generator/report.py
SLO report will not be sent if:
> fix: add post validation of SLI value

- slo_generator/exporters/base.py
- slo_generator/exporters/bigquery.py
Data was modified between exporters runs. This PR fixes it.
> Fix bug with multiple exporters

- .github/workflows/build.yml
- .github/workflows/release.yml
- .gitignore
- Dockerfile
- cloudbuild.yaml
- tests/unit/fixtures/ci_config.yaml
- tests/unit/fixtures/ci_knative_service.yaml
- tests/unit/fixtures/ci_slo.json
After Makefile refactor, change ci steps to accomodate changes.
> ci: Update CI steps

- slo_generator/api/main.py
- slo_generator/backends/cloud_service_monitoring.py
- slo_generator/backends/datadog.py
- slo_generator/exporters/base.py
- slo_generator/migrations/migrator.py
- slo_generator/utils.py
I just refactor some functionality in some parts of the code, waiting for the review! Anything not clear we can discuss it
> Inline variables that immediately returned 🪨 

- slo_generator/utils.py
Search yaml files in subdirectories from option `--slo-config`
> --slo-config: search yaml files in subdirectories

- slo_generator/utils.py
Reverts google/slo-generator#181
> Revert "--slo-config: search yaml files in subdirectories"

- samples/cloud_service_monitoring/slo_gae_app_availability.yaml
- samples/cloud_service_monitoring/slo_gae_app_availability_basic.yaml
- samples/cloud_service_monitoring/slo_gae_app_latency_basic.yaml
- samples/cloud_service_monitoring/slo_gke_app_availability_basic_deprecated.yaml
- samples/cloud_service_monitoring/slo_gke_app_latency_basic_deprecated.yaml
- slo_generator/backends/cloud_monitoring.py
- slo_generator/backends/cloud_service_monitoring.py
- slo_generator/backends/datadog.py
- slo_generator/compute.py
- slo_generator/exporters/base.py
- slo_generator/report.py
- slo_generator/utils.py
- tests/unit/fixtures/exporters.yaml
- tests/unit/test_compute.py
> fix: better exception handling and error logging

- docs/providers/cloud_monitoring.md
> add link to the filter document of Cloud Monitoring v3 API

- slo_generator/exporters/cloud_monitoring.py
There is no reason to call `ListMetricDesriptors` and `CreateMetricDescriptors` anymore. 
`CreateTimeSeries` now handles creating and updating `MetricDescriptors` explicitly. Customers using this script have observed 
```
ERROR - 429 Quota exceeded for quota metric 'Descriptor read requests' and limit 'Descriptor read requests per minute' of service 'monitoring.googleapis.com'
```
see: https://cloud.google.com/monitoring/custom-metrics/creating-metrics#auto-creation
> Remove call to list and create metricdescriptors

- .github/workflows/scorecard.yml
As recommended in [go/github-docs/security-recommendations](https://goto.google.com/github-docs/security-recommendations)
> chore: install the Scorecards Action

- slo_generator/backends/datadog.py
As discussed here #343 
I added the option to use query_bad instead of query_valid with the datadog backend. This is not a permanent fix as the subject should be investigated in more details with datadog. 
But as it stands, it will prevent false positive trigger.
> fix(datadog): Add query_bad to good_bad_ratio method

- slo_generator/report.py
Check if data is None already done at the beginning of the function. This code can't be reached.
> refactor: remove unreachable code

- setup.cfg
- slo_generator/exporters/bigquery.py
- slo_generator/report.py
- tests/unit/fixtures/slo_report_v2.json
Added metric would be useful in monitoring tools such as Prometheus/Grafana. It helps us better understand how much of the budget we are spending
> Fun/Consumed Budget Ratio metric

- slo_generator/exporters/bigquery.py
- slo_generator/report.py
- tests/unit/fixtures/slo_report_v2.json
Reverts google/slo-generator#413
I need to change the commit message to comply with Conventional Commits.
> Revert "Fun/Consumed Budget Ratio metric"

- slo_generator/exporters/bigquery.py
- slo_generator/report.py
- tests/unit/fixtures/slo_report_v2.json
Reverting google/slo-generator#415, as described in https://stackoverflow.com/questions/1078146/re-doing-a-reverted-merge-in-git
> Revert "Revert "Fun/Consumed Budget Ratio metric""
