google/slo-generator

- setup.py
Version 2.0.0 update of google-cloud-monitoring breaks linting + unittests, enforcing previous one.
> fix: Use version 1.x.x of google-cloud-monitoring

- slo_generator/report.py
Currently only the int part is taken leading to false alerts.
> alerting_burn_rate_threshold should be float

- slo_generator/exporters/bigquery.py
- slo_generator/utils.py
- tests/unit/test_utils.py
Decision to change the `timestamp_human` field to output standard UTC time because BigQuery and other exporters cannot make the difference. Appends timezone information if the backend can read it.
> fix: timestamp human in UTC format

- slo_generator/report.py
Fix BigQuery error when using Datadog / Dynatrace backends:
```
BigQueryError: [{"reason": "invalid", "location": "bad_events_count", "debugInfo": "", "message": "Cannot convert value to integer (bad value)
```
> fix: SLO Report - cast good / bad count to int

- docs/providers/datadog.md
- docs/providers/dynatrace.md
- docs/providers/prometheus.md
- docs/providers/stackdriver.md
- docs/shared/metrics.md
- slo_generator/backends/dynatrace.py
- slo_generator/compute.py
- slo_generator/exporters/base.py
- slo_generator/exporters/datadog.py
- slo_generator/exporters/dynatrace.py
- slo_generator/exporters/prometheus.py
- slo_generator/exporters/stackdriver.py
- tests/unit/fixtures/exporters.yaml
- tests/unit/test_compute.py
Add support to export multiple metrics with metrics exporters:
> feat: add support for multiple metrics in metrics exporters

- slo_generator/backends/datadog.py
Averaging on all values for `count` method does not return accurate good / bad values. This fixes it.
> fix: Datadog count

- slo_generator/constants.py
- slo_generator/exporters/base.py
- slo_generator/exporters/bigquery.py
- slo_generator/report.py
- tests/unit/fixtures/exporters.yaml
- tests/unit/fixtures/slo_report.json
- tests/unit/test_compute.py
This PR does the following:
Fixes #102
> feat: Add custom metadata to SLO configs

- docs/shared/metrics.md
- docs/shared/troubleshooting.md
- samples/prometheus/slo_prom_metrics_latency_distribution_cut.yaml
- slo_generator/compute.py
- slo_generator/exporters/base.py
- slo_generator/utils.py
- tests/unit/test_compute.py
- tests/unit/test_stubs.py
- tests/unit/test_utils.py
> Fix metrics exporter

- slo_generator/exporters/prometheus.py
When using the prometheus exporter, metrics _with the same labels_ get overwritten, resulting in persisting a single metric (out of the 4 intended).
As per [pushgateway](https://github.com/prometheus/pushgateway#exposed-metrics) :
> PUT is used to push a group of metrics. All metrics with the grouping key specified in the URL are replaced by the metrics pushed with PUT. 
Using POST with [pushadd_to_gateway](https://github.com/prometheus/client_python/blob/master/prometheus_client/exposition.py#L311) instead of [push_to_gateway](https://github.com/prometheus/client_python/blob/master/prometheus_client/exposition.py#L285) addresses this.
> chore: replace PUT by POST for prometheus exporter (push-gateway)

- Makefile
- setup.py
Seems like setuptools is broken on all CI tests. Replacing `python setup.py install` with `pip install .` works well. Not sure why ..
> fix: Error when running python setup.py install

- .gitignore
- Makefile
This PR updates the .gitignore and adds a few capabilities to the Makefile, which can now run all tests within Docker, build and push an API to Cloud Run, and run integration tests.
Basic commands are:
```
make # run everything
make unit # run unittests
make lint # run linting tests
make integration # run integration tests (require filling the samples/.env.sample file and sourcing it prior to running this)
```
but more granular commands exist to run only specific tests (cf Makefile).
> refactor: Update .gitignore and Makefile

- setup.py
This PRs lightens the slo-generator dependencies by making each backend / exporter have it's own set of dependencies, which can be installed separately when using backends / exporters. Goal: avoid dependency issues, meet best practices for Python packages.
> feat!: Split dependencies by backend

- slo_generator/backends/cloud_monitoring.py
- slo_generator/backends/cloud_service_monitoring.py
- slo_generator/backends/datadog.py
- slo_generator/backends/dynatrace.py
- slo_generator/backends/elasticsearch.py
- slo_generator/backends/prometheus.py
- slo_generator/compute.py
- slo_generator/constants.py
- slo_generator/exporters/base.py
- slo_generator/exporters/bigquery.py
- slo_generator/exporters/cloud_monitoring.py
- slo_generator/exporters/pubsub.py
- slo_generator/report.py
- slo_generator/utils.py
This PR adds support for the new slo-generator configuration v2 format, which basically:
* Upgrades the SLO config to a k8s-compatible one, and field names that make more sense
* Adds a new slo-generator config, that is a super-set of the existing error budget policy config (which is now obsolete)
> feat!: Support slo-generator config v2 format (core changes)

- slo_generator/cli.py
This PR upgrades the existing CLI to use Click, a library made for building much more robust CLIs (type checking, file existence check, OOTB flags, etc...).
The PR also renames the existing command: `slo-generator` --> `slo-generator compute` which makes it a breaking change, and adds two new commands, `slo-generator api` that runs the Cloud Functions Framework API, and `slo-generator migrate` to run the migration script from the CLI.
Fixes #120
> feat!: Upgrade slo-generator CLI to Click library

- README.md
- docs/deploy/cloudfunctions.md
- docs/providers/cloud_monitoring.md
- docs/providers/cloud_service_monitoring.md
- docs/providers/custom.md
- docs/providers/datadog.md
- docs/providers/dynatrace.md
- docs/providers/elasticsearch.md
- docs/providers/prometheus.md
- docs/providers/pubsub.md
- docs/shared/metrics.md
- docs/shared/migration.md
- docs/shared/troubleshooting.md
- samples/README.md
> docs: Update documentation for v2

- cloudbuild.yaml
Upload the build image to GCR and force the test suite to use the specific tagged version (instead of latest).
> Resolves #148

- slo_generator/migrations/migrator.py
`yaml.Loader` is subject to code execution using a specially formatted YAML file (`exploit.yml`):
```yml
!!python/object/apply:os.system ["id,whoami"]
```
and the following command:
```
slo-generator migrate -b exploit.yml
```
Credits to @Cimihan123 for finding this.
> fix: yaml loader security issue

- slo_generator/exporters/bigquery.py
It is better to let BigQuery compute a `row_id` instead of setting it based on the config fields, as it does not include metadata info, so if multiple SLOs have the same `service_name`, `slo_name`, `feature_name` and different metadata, there will be only 1 record instead of `n`
> fix: remove row_ids to solve de-duplication issues

- Makefile
- README.md
- docs/providers/prometheus.md
- samples/config.yaml
- slo_generator/exporters/prometheus_self.py
- tests/unit/fixtures/exporters.yaml
- tests/unit/test_compute.py
This is a rather hacky solution due to functions framework, but it works and removes the not-so-ideal dependency of pushgateway when running in an API mode. If needed, I can explain the motivation/use case a bit more.
> Add Prometheus Self exporter for API mode

- .github/workflows/build.yml
- .github/workflows/deploy.yml
> ci: replace deprecated `set-output` command with `GITHUB_OUTPUT` environment variable

- slo_generator/utils.py
currently, custom exporters are failing to load due to `capitalize`, this
will add the same logic (avoid capitalize custom class name) to `get_exporters` used in `get_backend`.
```
ERROR - Exporter not found in shared config.
Traceback (most recent call last):
File "/Users/pmishra/Data/failover_scheduler/slo/slo-generator/slo_generator/compute.py", line 127, in export
raise ImportError('Exporter not found in shared config.')
ImportError: Exporter not found in shared config.
```
> fix: support custom exporters

- .pre-commit-config.yaml
Seems a recent release of poetry broke isort.
Upgrade to at least 5.12.0 is required to fix.
Without this, the pre-commit hook is broken
Related link : https://levelup.gitconnected.com/fix-runtimeerror-poetry-isort-5db7c67b60ff
> Chore(build):fix isort version conflicting with newest poetry release

- Dockerfile
- Makefile
- docs/providers/splunk.md
- samples/config.yaml
- samples/splunk/slo_splunk_app_availability_query_sli.yaml
- samples/splunk/slo_splunk_app_availability_ratio.yaml
- samples/splunk/slo_splunk_app_availability_ratio2.yaml
- setup.cfg
- slo_generator/backends/cloud_monitoring_mql.py
- slo_generator/backends/splunk.py
- tests/unit/backends/test_splunk.py
- tests/unit/fixtures/config.yaml
- tests/unit/fixtures/splunk_generic_response.json
- tests/unit/test_compute.py
- tests/unit/test_stubs.py
Pretty straightforward, even though it's somehow a new exercice for me to go that deep into the code.
The goal of that PR is to implement a new backend provider : Splunk.
Since their APIs are the same, it should work both with Splunk CLoud or Splunk Enterprise (on premises)
I've tested it against the later, but should be able to test with both if needs be.
All new features are documented in the right directories and tests & mocks were implemented.
> Backend: Add Splunk as a backend provider

- slo_generator/utils.py
- tests/unit/fixtures/slo_report_v2.json
- tests/unit/test_utils.py
Hello,
utils.get_human_time() function format a UNIX timestamp as string to be stored into BigQuery.
But it replaces the timezone without dealing with the UTC time.
Using datetime.fromtimestamp() do the job well.
Tests have been updated accordingly.
Regards,
Sébastien
> fix: human time must not hard set the timezone

- slo_generator/backends/datadog.py
- slo_generator/utils.py
Hello,
Perf improvement. Avoid calling `/slo` endpoint because the response is not used.
As discussed, I left the call but I added a condition to run it only in debug mode. 
NB: SLO's data are available in the `/slo/history` endpoint call right after this one
Regards,
Sébastien
> refactor(backends/datadog): avoid useless call to Datadog API

- samples/config.yaml
- tests/unit/test_stubs.py
For local tests purposes, we may want to update the Datadog host URL used for Datadog API requests.
Example: testing rate limiting
Running a local NginX server acting as a Datadog API mock. We can set a dedicated rate-limit config without burning our Datadog instance (called "organization" by Datadog) quota.
Reminder: https://docs.datadoghq.com/api/latest/rate-limits/
> refactor(tests): allow to setup the Datadog host URL

- slo_generator/backends/open_search.py
- tests/unit/backends/test_opensearch.py
-- Actual Behaviour -- 
When using the open_search backend you cannot use filters in the query.
```
backend: open_search
error_budget_policy: 28days
method: good_bad_ratio
service_level_indicator:
index: "gravitee-request-*"
date_field: '@timestamp'
query_good:
filter:
- match:
api: some-data
- range:
status:
gte: 200
lt: 299
query_bad:
filter:
- match:
api: some-data
must_not:
range:
status:
lt: 299
goal: 0.99
```
The backend will throw the following error `TypeError: list indices must be integers or slices, not str`
-- Fix -- 
To avoid this error we must use append instead of directly assigning range = range_query (Furthermore, even if the actual code was working it would erase any range filter made in the yaml without informing the user which could have bring confusion).
> fix(open_search): change the way range is added to filters

- .github/workflows/release.yml
The username/password pair authentication method is obsolete now that 2FA is enforced since Jan 1, 2024.
> fix(ci): publish to PyPI with a Truster Publisher

- slo_generator/backends/open_search.py
- tests/unit/backends/test_opensearch.py
Everything is in the title but I will add a bit of details, 
While trying to find a way to optimize opensearch query time, I came accross the fact that we're using search endpoint but only using the result of `[“hits”][“total”][“value”]`. 
Meaning that we're consuming (a lot ?) of memory/time to calculate the _score and _ranking while not using it. 
So I switch it towards the count endpoint. Unfortunately it's quite hard to find documentation with precise benchmark of those to APIs, furthermore with intern request caching of Opensearch, even testing it manually can become quite a struggle. 
But in the end, it doesn't make sense to use the search endpoint if we just need to count. 
PS: Also we also weren't using the size: 0 with the search and that's definitely inducing performance issue.
> feat(opensearch): Performance optimization using count instead of search
